dc_showcase_homepage:
    pattern:  /
    defaults: { _controller: DCShowcaseBundle:Default:index, _locale: cs, name: 'test' }


dc_showcase_homepage_lang:
    pattern:  /{_locale}/{name}
    defaults: { _controller: DCShowcaseBundle:Default:index, _locale: en }
    requirements:
        _locale: cs|ru|en

login:
    pattern:   /login
    defaults:  { _controller: DCShowcaseBundle:Auth:login }
login_check:
    pattern:   /login_check