parameters:
#    dc_showcase.example.class: DC\ShowcaseBundle\Example

services:
#    dc_showcase.example:
#        class: %dc_showcase.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
