parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: delivery
    database_user: delivery
    database_password: ZunKvGwsGmTXVCwJ
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: eae08540c85cd71bf262314f61d18feb
    database_path: null
