<?php

namespace DC\ShowcaseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RestaurantMainRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RestaurantMainRepository extends EntityRepository
{
}
