<?php

namespace Proxies\__CG__\DC\ShowcaseBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Menu extends \DC\ShowcaseBundle\Entity\Menu implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setActive($active)
    {
        $this->__load();
        return parent::setActive($active);
    }

    public function getActive()
    {
        $this->__load();
        return parent::getActive();
    }

    public function setRemoved($removed)
    {
        $this->__load();
        return parent::setRemoved($removed);
    }

    public function getRemoved()
    {
        $this->__load();
        return parent::getRemoved();
    }

    public function setMonday($monday)
    {
        $this->__load();
        return parent::setMonday($monday);
    }

    public function getMonday()
    {
        $this->__load();
        return parent::getMonday();
    }

    public function setTuesday($tuesday)
    {
        $this->__load();
        return parent::setTuesday($tuesday);
    }

    public function getTuesday()
    {
        $this->__load();
        return parent::getTuesday();
    }

    public function setWednesday($wednesday)
    {
        $this->__load();
        return parent::setWednesday($wednesday);
    }

    public function getWednesday()
    {
        $this->__load();
        return parent::getWednesday();
    }

    public function setThursday($thursday)
    {
        $this->__load();
        return parent::setThursday($thursday);
    }

    public function getThursday()
    {
        $this->__load();
        return parent::getThursday();
    }

    public function setFriday($friday)
    {
        $this->__load();
        return parent::setFriday($friday);
    }

    public function getFriday()
    {
        $this->__load();
        return parent::getFriday();
    }

    public function setSaturday($saturday)
    {
        $this->__load();
        return parent::setSaturday($saturday);
    }

    public function getSaturday()
    {
        $this->__load();
        return parent::getSaturday();
    }

    public function setSunday($sunday)
    {
        $this->__load();
        return parent::setSunday($sunday);
    }

    public function getSunday()
    {
        $this->__load();
        return parent::getSunday();
    }

    public function setPlace(\DC\ShowcaseBundle\Entity\RestaurantPlace $place = NULL)
    {
        $this->__load();
        return parent::setPlace($place);
    }

    public function getPlace()
    {
        $this->__load();
        return parent::getPlace();
    }

    public function addMeal(\DC\ShowcaseBundle\Entity\Meal $meals)
    {
        $this->__load();
        return parent::addMeal($meals);
    }

    public function removeMeal(\DC\ShowcaseBundle\Entity\Meal $meals)
    {
        $this->__load();
        return parent::removeMeal($meals);
    }

    public function getMeals()
    {
        $this->__load();
        return parent::getMeals();
    }

    public function setPayDown($payDown)
    {
        $this->__load();
        return parent::setPayDown($payDown);
    }

    public function getPayDown()
    {
        $this->__load();
        return parent::getPayDown();
    }

    public function setRepeatType($repeatType)
    {
        $this->__load();
        return parent::setRepeatType($repeatType);
    }

    public function getRepeatType()
    {
        $this->__load();
        return parent::getRepeatType();
    }

    public function setRepeatAfter($repeatAfter)
    {
        $this->__load();
        return parent::setRepeatAfter($repeatAfter);
    }

    public function getRepeatAfter()
    {
        $this->__load();
        return parent::getRepeatAfter();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'active', 'payDown', 'removed', 'repeatType', 'repeatAfter', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday', 'place', 'meals');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}