<?php

namespace Proxies\__CG__\DC\ShowcaseBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Meal extends \DC\ShowcaseBundle\Entity\Meal implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setDescription($description)
    {
        $this->__load();
        return parent::setDescription($description);
    }

    public function getDescription()
    {
        $this->__load();
        return parent::getDescription();
    }

    public function setNeedSideDishes($needSideDishes)
    {
        $this->__load();
        return parent::setNeedSideDishes($needSideDishes);
    }

    public function getNeedSideDishes()
    {
        $this->__load();
        return parent::getNeedSideDishes();
    }

    public function setSeasonic($seasonic)
    {
        $this->__load();
        return parent::setSeasonic($seasonic);
    }

    public function getSeasonic()
    {
        $this->__load();
        return parent::getSeasonic();
    }

    public function setActive($active)
    {
        $this->__load();
        return parent::setActive($active);
    }

    public function getActive()
    {
        $this->__load();
        return parent::getActive();
    }

    public function setRemoved($removed)
    {
        $this->__load();
        return parent::setRemoved($removed);
    }

    public function getRemoved()
    {
        $this->__load();
        return parent::getRemoved();
    }

    public function addComponent(\DC\ShowcaseBundle\Entity\MealComponent $components)
    {
        $this->__load();
        return parent::addComponent($components);
    }

    public function removeComponent(\DC\ShowcaseBundle\Entity\MealComponent $components)
    {
        $this->__load();
        return parent::removeComponent($components);
    }

    public function getComponents()
    {
        $this->__load();
        return parent::getComponents();
    }

    public function setRestaurant(\DC\ShowcaseBundle\Entity\Restaurant $restaurant = NULL)
    {
        $this->__load();
        return parent::setRestaurant($restaurant);
    }

    public function getRestaurant()
    {
        $this->__load();
        return parent::getRestaurant();
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function setWeight($weight)
    {
        $this->__load();
        return parent::setWeight($weight);
    }

    public function getWeight()
    {
        $this->__load();
        return parent::getWeight();
    }

    public function setPrice($price)
    {
        $this->__load();
        return parent::setPrice($price);
    }

    public function getPrice()
    {
        $this->__load();
        return parent::getPrice();
    }

    public function setMonths($months)
    {
        $this->__load();
        return parent::setMonths($months);
    }

    public function getMonths()
    {
        $this->__load();
        return parent::getMonths();
    }

    public function addParkDomain(\DC\ShowcaseBundle\Entity\MealAttribute $parkDomains)
    {
        $this->__load();
        return parent::addParkDomain($parkDomains);
    }

    public function removeParkDomain(\DC\ShowcaseBundle\Entity\MealAttribute $parkDomains)
    {
        $this->__load();
        return parent::removeParkDomain($parkDomains);
    }

    public function getParkDomains()
    {
        $this->__load();
        return parent::getParkDomains();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'name', 'weight', 'price', 'description', 'needSideDishes', 'seasonic', 'months', 'active', 'removed', 'park_domains', 'components', 'restaurant');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}