<?php

namespace Proxies\__CG__\DC\ShowcaseBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class ParkDomain extends \DC\ShowcaseBundle\Entity\ParkDomain implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setChecked($checked)
    {
        $this->__load();
        return parent::setChecked($checked);
    }

    public function getChecked()
    {
        $this->__load();
        return parent::getChecked();
    }

    public function setLastCheck($lastCheck)
    {
        $this->__load();
        return parent::setLastCheck($lastCheck);
    }

    public function getLastCheck()
    {
        $this->__load();
        return parent::getLastCheck();
    }

    public function setRestaurant(\DC\ShowcaseBundle\Entity\Restaurant $restaurant = NULL)
    {
        $this->__load();
        return parent::setRestaurant($restaurant);
    }

    public function getRestaurant()
    {
        $this->__load();
        return parent::getRestaurant();
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function setDomain($domain)
    {
        $this->__load();
        return parent::setDomain($domain);
    }

    public function getDomain()
    {
        $this->__load();
        return parent::getDomain();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'name', 'domain', 'checked', 'lastCheck', 'restaurant');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}