<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/05/16 00:11:21

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=vuju',
  'username' => 'vuju',
  'password' => '3hvV4DyM5QXKZ9ba',
  'name' => 'doctrine',
)),);
