# Объект для ресторана
Partners:
  options:
    type: MyISAM
    collate: utf8_unicode_ci
    charset: utf8
  actAs: 
    Timestampable: ~
    I18n:
      fields: [descripton]
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    name: 
      type:     string(255)
      notnull:  true
    descripton: 
      type:     string
      default:  ""
    mainCookTypeId: 
      type:     integer
      notnull:  true
    long: 
      type:     decimal
      notnull:  true
    lat:  
      type:     decimal
      notnull:  true
    active: 
      type:     boolean
      default:  true
    validateResult:
      type:     enum
      values:   ["Not validated","Approved","Canceled"]
    address:
      type:     string
      notnull:  true
    creatorId:
      type:     integer
      notnull:  true
    lastEditorId:
      type:     integer
      notnull:  true
    selfDelivery:
      type:     boolean
      default:  false
      notnull:  true
    notyfyEmail:
      type:     string(255)
      notnull:  true
    notyfyPhone:
      type:     string(255)
      notnull:  true

# Время работы ресторана
WorkTime:
  options:
    type:     MyISAM
    collate:  utf8_unicode_ci
    charset:  utf8
  actAs: 
    Timestampable: ~
  columns:
    id:
      type:     integer(8)
      fixed:    false
      unsigned: false
      primary:  true
      autoincrement: true
    dayOfWeek:
      type:     integer(1)
      notnull:  true
    startWorkTime:
      type:     time
      notnull:  true
    endWorkTime:
      type:     time
      notnull:  true
    minDeliverySumBeforeWork:
      type:     decimal
      notnull:  true
    minDeliverySumInWork:
      type:     decimal
      notnull:  true
    minDeliverySumAfterWork:
      type:     decimal
      notnull:  true
    deliveryPriceBeforeWork:
      type:     decimal
      notnull:  true
    deliveryPriceInWork:
      type:     decimal
      notnull:  true
    deliveryPriceAfterWork:
      type:     decimal
      notnull:  true

# Типы кухонь например "Таджикская" и "Узбекская"
CookType:
  options:
    type: MyISAM
    collate: utf8_unicode_ci
    charset: utf8
  actAs: 
    Timestampable: ~
    I18n:
      fields: [name]
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    name:
      type:     string
      notnull:  true

# Категории меню например "Супы" и "Закуски"
MenuCategory: 
  options:
    type: MyISAM
    collate: utf8_unicode_ci
    charset: utf8
  actAs: 
    Timestampable: ~
    I18n:
      fields: [name, descripton]
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    name:
      type:     string(255)
      notnull:  true
    descripton:
      type:     string(255)
      notnull:  true

# Наборы меню
Menu:
  options:
    type: MyISAM
    collate: utf8_unicode_ci
    charset: utf8
  actAs: 
    Timestampable: ~
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    startAt:
      type:     datetime
      notnull:  true
    endAt:
      type:     datetime
      notnull:  true
    dayOfWeek:
      type:     integer
      default:  0
      notnull:  true
    userType:
      type:     integer
      default:  0
      notnull:  true
    daysToOrder:
      type:     integer
      default:  0
      notnull:  true
    partnerId:  
      type:     integer
      default:  0
      notnull:  true

# Содержание набора меню
MenuItem:
  options:
    type: MyISAM
    collate: utf8_unicode_ci
    charset: utf8
  actAs: 
    Timestampable: ~
    I18n:
      fields: [name, descripton]
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    menuId:
      type: integer
      default: 0
    name:
      type:     string(255)
      notnull:  true
    descripton:
      type:     string(255)
      notnull:  true
    accessTimeStart:
      type:     time
      notnull:  true
    accessTimeEnd:
      type:     time
      notnull:  true
    price: 
      type:     decimal
      notnull:  true
    menuCategoryId:
      type:     integer
      notnull:  true
    showInTop:
      type:     boolean
      default:  false

# Картинки для содержания меню
MenuItemImage:
  options:
    type: MyISAM
    collate: utf8_unicode_ci
    charset: utf8
  actAs: 
    Timestampable: ~
    I18n:
      fields: [descripton]
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    path:
      type:     string(255)
      notnull:  true
    descripton:
      type:     string(255)
      notnull:  true
    menuItemId:
      type:     integer
      default:  0
      notnull:  true

# Компоненты для содержания меню 
Component:
  options:
    type: MyISAM
    collate: utf8_unicode_ci
    charset: utf8
  actAs: 
    Timestampable: ~
    I18n:
      fields: [descripton]
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true

# Дополнительные компоненты, которые клиент может дозаказать. Сюда пойдут прилохи всякие
AdComponet:
  options:
    type: MyISAM
    collate: utf8_unicode_ci
    charset: utf8
  actAs: 
    Timestampable: ~
    I18n:
      fields: [descripton]
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true

# Параметры блюда например вес и содержания цианистого калия
Param:
  options:
    type: MyISAM
    collate: utf8_unicode_ci
    charset: utf8
  actAs: 
    Timestampable: ~
    I18n:
      fields: [descripton]
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true

# Корзины пользователя
Basket:
  options:
    type: MyISAM
    collate: utf8_unicode_ci
    charset: utf8
  actAs: 
    Timestampable: ~
    I18n:
      fields: [descripton]
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true

# Блюда в корзине
BasketItem:
  options:
    type: MyISAM
    collate: utf8_unicode_ci
    charset: utf8
  actAs: 
    Timestampable: ~
    I18n:
      fields: [descripton]
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true

# Дополнительные компоненты к блюдам в корзине
AdComponetsBasket:
  options:
    type: MyISAM
    collate: utf8_unicode_ci
    charset: utf8
  actAs: 
    Timestampable: ~
    I18n:
      fields: [descripton]
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true

# Заказ пользователя
XOrder:
  options:
    type: MyISAM
    collate: utf8_unicode_ci
    charset: utf8
  actAs: 
    Timestampable: ~
    I18n:
      fields: [descripton]
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true

#Категории бонусов
BonusCategory:

# Бонусы
BonusItem:

# Заказ бонусов
BonusOrder: